# -*- coding: utf-8 -*-
"""RSSI 분리 로직

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1avnazchNQa_-hUXZqboH1o9vHAbedruF
"""

import time                                                                      #시간 관려 함수 사용
import RPi.GPIO as GPIO                                                          # 라즈베리 GPIO 제어 라이브러리
import csv                                                                       # CSV 파일로 데이터 저장, 나중에 데이터 확인용
from datetime import datetime

class RSSISeparator:                                                             # RSSI로 분리 판단하는 시스템 구축
    def __init__(self, alpha=0.15, threshold=-80, duration=2.0):                  # 파라미터 설정 // 이 값들은 추후 바꿔가면서 데이터 얻어봐야할듯.

        self.alpha = alpha                                                         # EWMA 가중치 (민감도)--> 알파 값이 높으면 최신 값을 믿어서 빠르게반응,알파값이 낮으면 과거 값유지(반응이 느리지만 안정적)
        self.threshold = threshold                                                 # 분리 임계값 (dBm) --> RSSI 값이 이보다 낮으면 위첨하다는 것.
        self.duration = duration                                                   # 신호 저하 유지 시간(초), 신호가 일정시간 유지를 해야 분리 확정

                                                                                 # 상태 변수
        self.filtered_rssi = None                                                  # 필터링된 RSSI 값을 저장하는 변수. 처음에는 값이 없으니까 NONE
        self.timer_start = None                                                    # RSSI가 나빠진 시작 시간 저장, 신호가 임계치 아래로 떨어지면 시간 기록을 시작하고 신호가 회복되면 다시 NONE으로 초기화
        self.is_detached = False                                                   # 분리여부를 확인하는 것으로 FALSE의 경우 아직 로직이 작동중이고 TRUE로 바뀌면 분리가 완료되어 루프가 종료됨.

                                                                                 # 로그 파일 설정--> CSV파일을 열고 데이터를 계속 쌓을 파일, 실행시간 기반으로 데이터를 저장 / 시스템의 모든 판단을 남기기위함
        self.log_file = f"rssi_log_{datetime.now().strftime('%m%d_%H%M')}.csv"     # 파일 이름 생성 datetime.now(): 현재시간, strftime('%m%d_%H%M') : 형식변환, 실행할떄마다 파일 겹치지 않게 하기 위해 시간 기준으로 로그 관리
        with open(self.log_file, 'w', newline='') as f:                            # CSV 파일을 쓰기 모드로 열기
            writer = csv.writer(f)                                                 # CSV 파일에 데이터를 쓰기 위한 객체 생성 -> 파이썬 리스트를 CSV 한 줄로 변환한다.
            writer.writerow(['Timestamp', 'Raw_RSSI', 'Filtered_RSSI', 'Status'])  # CSV 첫 줄 작성(헤더)


                                                                                 # 리눅스 커널에서 RSSI값을 읽어서 숫자로 변환하는 함수
                                                                                  ## 즉 이 함수는 리눅스 커널에서 현재 wi-fi 신호 세기를 읽어와 숫자로 변환해주는 센서 역할

    def get_raw_rssi(self):                                                       # RSSI 값을 가져오는 함수 정의 --> 이게 뭐 커널이 어쩌고 다른 방법으로는 소켓잉 어쩌고 (iwconfig / iw / socket)” 이런 방식도 있음.
        """커널(/proc/net/wireless)에서 실시간 RSSI를 파싱함 (2~3단계 근거)"""
        try:                                                                      # 에러 발생 가능성 대비 즉 파일이 없거나 읽기 실패 대비
            with open("/proc/net/wireless", "r") as f:                             # 커널 파일 열기(읽기 모드) --> 리눅스가 네트워크 상태를 보여주는 가상 파일
                lines = f.readlines()                                              # 파일 전체를 줄 단위로 읽음 (리스트 형태)
                for line in lines:                                                 # 한 줄씩 검사 시작
                    if "wlan0" in line:                                            # 여러 네트워크 중에서 사용하는 wi-fi만 선택
                        parts = line.split()                                       # 공백 기준으로 문자열 분리
                        return float(parts[3].replace('.', ''))                    # 데이터에서 RSSI값을 뽑고 이것을 float 형태로 반환, 즉 문자열 상태의 RSSI 값을 숫자로 변환
        except Exception as e:                                                       # 에러 발생 시 실행
            print(f"Error reading RSSI: {e}")                                        # 에러 내용 출력
        return None                                                                  # 실패하면 None 반환 즉 값 못 읽었다는 신호


                                                                                 # 앞에서 파일을 만들었고 이제는 이 파일에 현재 상태 데이터를 csv 파일에 기록하는 함수.
    def log_data(self, raw, filtered, status):                                    # raw : 원본 RSSI, filtered : 필터된 RSSI, status : stable, warning, detached (즉 분리 알림 상태)
        with open(self.log_file, 'a', newline='') as f:                           # CSV 파일을 append 모드로 열기 (기존 내용 유지 + 뒤에 추가, 즉 누적 기록)
            writer = csv.writer(f)                                                # CSV 작성 도구 생성 : 리스트를 CSV 형식을 변환하는 것.
            writer.writerow([time.time(), raw, filtered, status])                 # 한 줄 데이터 기록 // time.time() : 현재시간


                                                                                 # RSSI를 계속 감시하면서 분리 조건이 될 때까지 반복 실행하는 메인 루프
    def run(self):                                                                # 이 함수가 호출되면 시스템이 실제로 동작을 시작한다.
        print(f"--- 분리 알고리즘 가동 (임계값: {self.threshold}dBm) ---")        # 시작 메세지 출력 및 현재의 임계치 보여줌
        try:                                                                       # 예외 처리 (파일 읽기 실패나 RSSI 읽기 오류 등의 예외 상황)
            while not self.is_detached:                                              # 반복 루프를 두어서 분리 될때까지 계속 감시하는 장치
                raw_rssi = self.get_raw_rssi()                                       # RSSI 값 읽기 .. /proc/net/wireles을 읽고 wlan0을찾고 RSSI를 반환함.
                if raw_rssi is None: continue                                        # 값 못 읽었으면 건너뛰기, 즉 RSSI 일기 실패 시 다음 루프로

                                                                                  # 1. EWMA 필터 적용 (1단계 하드웨어 노이즈 제거)
                if self.filtered_rssi is None:                                      # EWMA는 이전 값이 있어야 가능하다. 처음에는 이전 값이 없음
                    self.filtered_rssi = raw_rssi                                   # 따라서 첫 값이면 그냥 그대로 사용
                else:
                    self.filtered_rssi = (self.alpha * raw_rssi) + ((1 - self.alpha) * self.filtered_rssi)  # RSSI 공식
                status = "STABLE"                                                    # 상태 초기화, 기본 상태는 STABLE이고 조건에 따라 WARNING과 DETACHED가 있음.

                                                                                  # 2. 판단 로직 (히스테리시스 및 타이머)
                if self.filtered_rssi < self.threshold:                            # RSSI가 임계치보다 낮으면 위험상태 진입
                    status = "WARNING"                                             # WARNING으로 상태 변경ㄴ
                    if self.timer_start is None:                                   # 타이머가 아직 시작 안되었으면
                        self.timer_start = time.time()                             # 현재 시간을 기록

                    elapsed = time.time() - self.timer_start                       # 경과 시간을 계산
                    if elapsed >= self.duration:                                   # 설정 시간 이상 지속되면
                        self.execute_detach()                                      # 분리 실행 -> GPIO가 켜지면서 분리가 작동.
                        status = "DETACHED"                                        # DETACHED 즉 분리가 완료되었다고 상태를 변경
                else:
                    self.timer_start = None # 신호 복구 시 타이머 초기화           # 만약 신호가 회복되면 타이머가 초기화

                                                                                  # 3. 데이터 로깅
                self.log_data(raw_rssi, self.filtered_rssi, status)                # CSV 파일에 데이터 저장, 지금 순간 상태를 파일에 기록
                print(f"[{status}] Raw: {raw_rssi} | Filtered: {self.filtered_rssi:.2f}")   # 콘솔에 현재 상태 출력

                time.sleep(0.1)                                                 # 100ms 샘플링 (커널 업데이트 주기 고려)

        except KeyboardInterrupt:                                                # 예외 처리
            print("중단됨")                                                      # 프로그램 정상적으로 멈췄다는 표시
        finally:
            GPIO.cleanup()                                                        # 항상 종료가 되면 GPIO 상태 초기화

    def execute_detach(self):                                                    # 분리 동작을 수행하는 함수
        print("🚨 [분리 실행] 통신 한계점 도달. 유닛을 분리합니다.")
                                                                                  # GPIO 핀 제어 (전자석 또는 서보 모터)
        GPIO.output(18, GPIO.HIGH)                                                 # GPIO 18번 핀에 HIGH 출력
        time.sleep(1)                                                              # 1초 대기
        self.is_detached = True                                                    # 상태를 변경하여 run 루프 종료

# GPIO 초기화
GPIO.setmode(GPIO.BCM)
GPIO.setup(18, GPIO.OUT)

if __name__ == "__main__":
    separator = RSSISeparator(alpha=0.2, threshold=-82, duration=2.5)
    separator.run()